It's been sooo long...

diff --git a/subgau b/subgau
--- a/subgau
+++ b/subgau
@@ -4,7 +4,7 @@
 # GAUSSIAN JOB SUBMISSION SCRIPT
 # ------------------------------
   unset outnam ; unset wrkdir ; unset gauroot ; unset comando
-  unset inp ; unset opt ; unset add ; unset vrb
+  unset inp ; unset opt ; unset add ; unset vrb ; unset mrg
   declare -a inp ; declare -a opt
   declare -i nsec=0 ; declare -i maxsec=3
   function usage {
@@ -17,6 +17,7 @@
     echo "    -a kwr  : add keyword kwr to the route section on-the-fly"
     echo "    -nonice : bully other processes to run faster"
     echo "    -k      : do not overwrite the log file (append output)"
+    echo "    -m      : multi-job mode submitting all inputs at once"
     echo "    -v      : verbose submission"
     echo "    -h      : print this message and exit"
     exit 0
@@ -34,11 +35,14 @@
 #  jblsub="/home/j.bloino/bin/gxx_qsub.py"
   jblsub="/home/f.egidi/bin/mycopy_gxx_qsub.py"
   if [[ "${HOSTNAME}" = "avogadro1" && -x "${jblsub}" ]]; then
+    arc='-n'
 #   Sort options from job files
     while [[ -n "${1}" ]]; do
       case "${1}" in
         *.com | *.gjf ) inp=( "${inp[@]}" "${1}" );;
+        -m            ) mrg='-m';;
         -v            ) vrb='-v';;
+        -n            ) arc='';;
         -h | --help   ) "${jblsub}" "-h"; exit 0;;
         --            ) ;;
         *             ) opt=( "${opt[@]}" "${1}" );;
@@ -47,14 +51,16 @@
     if [[ "${#inp[@]}" -eq 0 ]]; then echo "ERROR: no valid input file"; exit 1; fi
 #   Submit all jobs
     for input in ${inp[*]}; do
+      if [[ "${mrg}" = '-m' ]]; then input="${inp[*]}"; fi
       comando="$( echo "${jblsub}" "${opt[*]}" -- "${input}" )"
       if [[ "${vrb}" = '-v' ]]; then echo "${comando}"; fi
       eval "${comando}"
 #     Submission journal
-      if [ "${USER}" = 'f.egidi' ]; then
+      if [[ "${USER}" = 'f.egidi' ]] && [[ "${arc}" = '-n' ]]; then
         echo "$( date )" " ; " "$( pwd )" >> /home/f.egidi/.mysubs
         echo "  "${comando} >> /home/f.egidi/.mysubs
       fi
+      if [[ "${mrg}" = '-m' ]]; then break; fi
     done
 # ----------------------
 # INTERACTIVE SUBMISSION
@@ -81,10 +87,10 @@
     if [ "${#inp[@]}" -eq 0 ]; then echo "ERROR: no valid input file"; exit 1; fi
 #   Recover Gaussian executable if explicitly specified via -g
     if [ -n "${gauroot}" -a -d "${gauroot}" ]; then
-      if [ -x "${HOME}/bin/setgaussian" ]; then
-        . ${HOME}/bin/setgaussian ${vrb} -g "${gauroot}" || echo "ERROR: Encountered problems with Gaussian path ${gauroot}"; exit 1
-      elif [ -x "$( which setgaussian )" ]; then
-        . setgaussian ${vrb} -g "${gauroot}" || echo "ERROR: Encountered problems with Gaussian path ${gauroot}"; exit 1
+      if [ -x "${HOME}/bin/setgaussian.sh" ]; then
+        . ${HOME}/bin/setgaussian.sh ${vrb} -g "${gauroot}" || echo "ERROR: Encountered problems with Gaussian path ${gauroot}"; exit 1
+      elif [ -x "$( command -v setgaussian.sh )" ]; then
+        . setgaussian.sh ${vrb} -g "${gauroot}" || echo "ERROR: Encountered problems with Gaussian path ${gauroot}"; exit 1
       else
         echo "ERROR: script setgaussian not found"; exit 1
       fi
@@ -118,7 +124,7 @@
       if [ ! -f "${file}" ]; then echo "ERROR: input file ${file} not found"; continue; fi
 #     Add keywords to the input on the fly
       if [ -n "${add}" ]; then
-        if [ ! -x "$( which sedi )" ]; then echo "ERROR: you need the sedi utility to do this"; exit 1; fi
+        if [ ! -x "$( command -v sedi )" ]; then echo "ERROR: you need the sedi utility to do this"; exit 1; fi
         input="${file%.*}.tmp"
         cp -- "${file}" "${input}"
         for x in {"p","","t"}; do sedi ${vrb} -s -b "#${x} " "#${x}" "#${x} ${add}" "${input}"; done
diff --git a/worktree b/worktree
--- a/worktree
+++ b/worktree
@@ -7,51 +7,64 @@
     exit 0
   fi
 # Gaussian must be correctly set up
-  if [ -z "${gdvroot}" ]; then
-    if [ -z "${g09root}" ]; then
-      echo 'ERROR: Gaussian environment not set'; exit 1
-    else
-      gau='g09'; gauroot="${g09root}"
-    fi
+  if   [[ -x "${gdvroot}/gdv/gdv" ]]; then
+    gau="gdv"; gauroot="${gdvroot}"
+  elif [[ -x "${g16root}/g16/g16" ]]; then
+    gau="g16"; gauroot="${g16root}"
+  elif [[ -x "${g09root}/g09/g09" ]]; then
+    gau="g09"; gauroot="${g09root}"
   else
-    gau='gdv'; gauroot="${gdvroot}"
+    echo "ERROR: Gaussian environment not properly set"; exit 1
   fi
 # Handle the nutil
-  if [ ! -d "nutil" ]; then
+  if [[ ! -d "nutil" ]]; then
     mkdir "nutil"
-    cp -- "${gauroot}/${gau}/bsd/nutil.make" "nutil/"
+    cp -p -- "${gauroot}/${gau}/bsd/nutil.make" "nutil/"
     getx "a2nucf" "utilam"
     sed -i "/^OBJAM\ =/s/=/=\ a2nucf.o/" "nutil/nutil.make"
+    sed -i "/^LOBJAM/s/evlind.lo//" "nutil/nutil.make"
   fi
 # Define the link you want in your working
   link="${1}"
-  if [ "${link}" = "nutil" ]; then exit 0; fi
-  if [ ! -f "${gauroot}/${gau}/${link}.F" ]; then
+  if [[ "${link}" == "nutil" ]]; then exit 0; fi
+  if [[ ! -f "${gauroot}/${gau}/${link}.F" ]]; then
     echo "ERROR: Link ${link}.F does not exist"; exit 1
-  elif [ -d "${link}" ]; then
+  elif [[ -d "${link}" ]]; then
     echo "ERROR: You already have a ${link} directory"; exit 1
   fi
-  if [ ! -d "${link}" ]; then
+  if [[ ! -d "${link}" ]]; then
     ink="$( echo "${link}" | sed s/l// )"
     mkdir "${link}"
     line="$( grep -m 1 -- "Deck" "${gauroot}/${gau}/${link}.F" | tr '[:upper:]' '[:lower:]' )"
     deck=(${line})
     rout="${deck[1]}"
     getx "${rout}" "${link}"
-    cp -- "${gauroot}/${gau}/bsd/link.make" "${link}/${link}.make"
-    sed -i "s/502/${ink}/g" "${link}/${link}.make"
-    sed -i "/^OBJ${ink}\ =/s/=/=\ ${rout}.o/" "${link}/${link}.make"
+    if [[ "${link}" == "l1" ]] || [[ "${link}" == "l9999" ]]; then
+      cp -p -- "${gauroot}/${gau}/bsd/${link}.make" "${link}/${link}.make"
+    else
+      cp -p -- "${gauroot}/${gau}/bsd/link.make" "${link}/${link}.make"
+      sed -i "s/502/${ink}/g" "${link}/${link}.make"
+      sed -i "/^OBJ${ink}\ =/s/=/=\ ${rout}.o/" "${link}/${link}.make"
+    fi
   fi
 # Take care of the Makefile
-  if [ ! -f "Makefile" ]; then
-    cp -- "${gauroot}/${gau}/bsd/tree.make" "Makefile"
+  if [[ ! -f "Makefile" ]]; then
+    cp -p -- "${gauroot}/${gau}/bsd/tree.make" "Makefile"
     sed -i "/^all:/s/all:.*/all:\ nutilx\ ${link}x\ edir/" "Makefile"
     sed -i "/^lall:/s/lall:.*/lall:\ nutilxl\ nutillx\ ${link}xl\ ldir/" "Makefile"
+#   Add info on Gaussian version to file
+    tmpfil="$( mktemp )" ; mv "Makefile" "${tmpfil}"
+    echo "# File taken from ${gauroot}" > "Makefile"
+    cat "${tmpfil}" >> "Makefile"; rm -- "${tmpfil}"
   fi
-  if [ -z "$( grep -- "^all:.*${link}x" "Makefile" )" ]; then
+  if [[ -z "$( grep -- "^all:.*${link}x" "Makefile" )" ]]; then
     sed -i "/^all:/s/nutilx/nutilx\ ${link}x/" "Makefile"
   fi
-  if [ -z "$( grep -- "^lall:.*${link}xl" "Makefile" )" ]; then
+  if [[ -z "$( grep -- "^lall:.*${link}xl" "Makefile" )" ]]; then
     sed -i "/^lall:/s/nutillx/nutillx\ ${link}xl/" "Makefile"
+  fi
+# Fix file permissions
+  if [[ "$( groups )" == *gaudev* ]]; then
+    chgrp -c -- gaudev */*.F
   fi
   exit 0
