Minor adjustments to adapt to avogadro

diff --git a/subgau b/subgau
--- a/subgau
+++ b/subgau
@@ -31,7 +31,8 @@
 # --------------
 # PBS SUBMISSION
 # --------------
-  if [ -x "/home/j.bloino/bin/subgau.py" ]; then
+  jblsub="/home/j.bloino/bin/gxx_qsub.py"
+  if [ -x "${jblsub}" ]; then
 #   Sort options from job files
     for input in "${@}"; do
       if [[ ${input} = *".com" ]]; then
@@ -40,10 +41,10 @@
         opt=( "${opt[@]}" "${input}" )
       fi
     done
-    if [ "${#inp[@]}" -eq 0 ]; then echo "ERROR: no valid input file"; exit 1; fi
+    if [[ "${#inp[@]}" -eq 0 ]] && [[ "${opt[0]}" != '-h' ]]; then echo "ERROR: no valid input file"; exit 1; fi
 #   Submit all jobs
     for input in "${inp[*]}"; do
-      comando="$( echo "/home/j.bloino/bin/subgau.py" "${opt[*]}" "${input}" )"
+      comando="$( echo "${jblsub}" "${opt[*]}" "${input}" )"
       eval "${comando}"
 #     Submission journal
       if [ "${USER}" = 'f.egidi' ]; then
